In [3]:
import pandas as pd
import numpy as np
import pprint 

#Random number in 100 element array median
pp = pprint.PrettyPrinter()
def median_from_int_array(max_sample=1, array_size=1, keys=['np_array', 'np_med']) :
    int_array = np.random.randint(max_sample, size=array_size)
    obj = {keys[0]:int_array, keys[1]:np.median(int_array)} 
    return obj

val = median_from_int_array(100, 100)
pp.pprint(val['np_array'])
pp.pprint('Median: '+ str(val['np_med']))

array([56, 65, 99, 78,  8, 77, 39, 53, 72, 88, 69,  5, 88, 23, 59,  9, 47,
       99, 35, 81, 89, 14, 53, 44, 85,  1, 17, 40, 13, 93, 18, 77, 97, 74,
        6, 47, 63, 73, 66,  9,  9,  2, 35, 40,  2, 74, 40, 78, 18, 60, 26,
       44, 59,  7,  7, 34, 77, 92, 21, 80, 62, 89, 91, 48, 43, 42, 64, 36,
       43, 97, 87, 93, 74, 30, 98, 54, 86, 80, 75, 44,  5, 98, 88, 58, 51,
       75, 57, 23, 22, 74, 31, 72, 28, 34, 38,  3,  2, 24,  8, 38])
'Median: 52.0'


In [4]:
#Factorial Rework
def factorial_by_np():
   

    val_int = int(input('Ingrese factorial a calcular: '))
    pp.pprint('Factorial: {0}'.format(np.math.factorial(val_int)))
factorial_by_np()

('Factorial: '
 '93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000')


In [5]:
#series rework
def series_sum_by_np(x, y):

   

    np_array = np.arange(y+1)
    slice_array = np_array[x:y+1]
    pp.pprint('Valores a sumar: {0}'.format(slice_array))
    sum_array = np.sum(slice_array)
    pp.pprint('Sumatoria: {0}'.format(sum_array))

val_start = int(input('Ingrese inicio serie: '))
val_end = int(input('Ingrese final serie: '))
assert val_end > val_start, 'El valor final de la serie tiene que ser mayor al inicial'

series_sum_by_np(val_start, val_end)

('Valores a sumar: [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  '
 '24  25  26  27\n'
 '  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45\n'
 '  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63\n'
 '  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81\n'
 '  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99\n'
 ' 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117\n'
 ' 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135\n'
 ' 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153\n'
 ' 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171\n'
 ' 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189\n'
 ' 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207\n'
 ' 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225\n'
 ' 226 227 228 229 230 231 232 233 234 235 

In [6]:
#openqube salaries
columna_salario_bruto = 47
columna_salario_neto = 48

def clean_value(val):
  
    val = str(val).replace('.','').replace(',', '')
    if len(str(val)) == 0 or str(val) == 'nan':
        return 0
    if np.isnan(float(val)):
        return 0
    return (int(float(val)))

def parse_csv(filename, column='0'):
    csv_dataframe = pd.read_csv(filename).fillna(0).to_numpy() 

    raw_salary = np.array([clean_value(employee[columna_salario_bruto]) for employee in csv_dataframe])
    net_salary = np.array([clean_value(employee[columna_salario_neto]) for employee in csv_dataframe])
   
    pp.pprint(raw_salary)
    pp.pprint(net_salary)

    return {'bruto':raw_salary, 'neto':net_salary}
    
def employee_median_salary(salary_array):
    return np.median(salary_array)
def employee_mean_salary(salary_array):
    return np.mean(salary_array)

salaries = parse_csv('salarios_openqube_2020.02.csv')
pp.pprint("Mediana salarios netos: {0}".format(employee_median_salary(salaries['neto'])))
pp.pprint('Medio salarios netos: {0}'.format(employee_mean_salary(salaries['neto'])))

array([ 530000,  790000, 1600000, ...,  472500,  860000,  850000],
      dtype=int64)
array([ 43000,  63000, 127000, ...,  45753,     72,  65000], dtype=int64)
'Mediana salarios netos: 75000.0'
'Medio salarios netos: 18710307.28916602'
